### ISSUE TITLE
I ran into a problem when using command line fine-tuning

### ISSUE THREAD

**Issue by rainbownmm** [SalesforceAIResearch/uni2ts#10]
I ran into a problem when using command line fine-tuning

Thanks for the great work, I encountered the error when using the command line provided by the following tutorial. My environment installation should be no problem. Using your model, it performs very well when making zero-sample predictions, but I want to make it more To go further, I therefore use the following command line for fine-tuning:
----------------------
python -m cli.finetune \
   run_name=example_run \
   model=moirai_1.0_R_small \
   data=etth1 \
   val_data=etth1 
----------------------
But unfortunately I am not very familiar with the hydra framework, so I got the following error
----------------------
Traceback (most recent call last):
   File "/home/duyuyang/miniconda3/envs/uni2ts/lib/python3.10/runpy.py", line 196, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "/home/duyuyang/miniconda3/envs/uni2ts/lib/python3.10/runpy.py", line 86, in _run_code
     exec(code, run_globals)
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/cli/eval.py", line 84, in <module>
     main()
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/main.py", line 90, in decorated_main
     _run_hydra(
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
     _run_app(
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
     run_and_report(
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
     raise ex
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
     return fun()
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
     lambda: hydra.run(
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 105, in run
     cfg = self.compose_config(
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
     cfg = self.config_loader.load_configuration(
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
     return self._load_configuration_impl(
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 244, in _load_configuration_impl
     parsed_overrides, caching_repo = self._parse_overrides_and_create_caching_repo(
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/_internal/config_loader_impl.py", line 228, in _parse_overrides_and_create_caching_repo
     parsed_overrides = parser.parse_overrides(overrides=overrides)
   File "/home/duyuyang/code/uni2ts/uni2ts-main/uni2ts-main/venv/lib/python3.10/site-packages/hydra/core/override_parser/overrides_parser.py", line 96, in parse_overrides
     raise OverrideParseException(
hydra.errors.OverrideParseException: LexerNoViableAltException:
                            ^
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details
----------------------
The data set used is still the etth1 data set in your sample script for the time being. How can I adjust it? I checked and found that there was a problem with the configuration file path in finetune.py, but I didn’t seem to find the configuration file after checking. There is a problem with the path. The env looks like this:
![image](https://github.com/SalesforceAIResearch/uni2ts/assets/120607490/f7a7a054-f66f-4114-961f-15bfda4b2c2b)
I don't know if there is a problem with this

**Comment by gorold** [comment]
It might be the formatting of the command - try entering it in one line. 

You need to run the previous few commands from the example to set up your fine-tuning dataset too.

`echo "CUSTOM_DATA_PATH=PATH_TO_SAVE" >> .env`

`python -m uni2ts.data.builder.simple ETTh1 dataset/ETT-small/ETTh1.csv --date_offset '2017-10-23 23:00:00'`

**Comment by rainbownmm** [comment]
Thanks for the answer. There is no problem with the steps. I failed to run it in wsl, but it ran successfully in the windows environment. I would like to ask how much CUDA memory is needed to fine-tune the three models of small base large.

**Comment by rainbownmm** [comment]
I used a machine with a 16G GPU. I saw that the small model only had 55.3M, but it still showed cuda out of memory .

**Comment by gorold** [comment]
For the small model, we can train with a batch size of 128 with an A100-40G, not too sure about the exact requirements for the other models, you can test it out with smaller batch sizes or use gradient accumulation.

**Comment by zqiao11** [comment]
> I used a machine with a 16G GPU. I saw that the small model only had 55.3M, but it still showed cuda out of memory .

Based on my experience, the CUDA memory is around 24 GB to run the given finetuning cli example using the default config.

**Comment by rainbownmm** [comment]
Thanks for your answers, I'll give it a try

**Comment by Riofd** [comment]
> Thanks for your answers, I'll give it a try

Hi, is it effective by reducing batch_size? I changed `cli/finetune/default.yaml` with `batch_size=1`, but it still errors on RTX3090 24GB.

**Comment by Riofd** [comment]
> > Thanks for your answers, I'll give it a try
> 
> Hi, is it effective by reducing batch_size? I changed `cli/finetune/default.yaml` with `batch_size=1`, but it still errors on RTX3090 24GB.
I solved it by distributed training with two GPUs.
