### ISSUE TITLE
Hello, I encountered many issues while fine-tuning with my own data, possibly related to the configuration file of the dataset. Is there a description available for the dataset configuration file?

### ISSUE THREAD

**Issue by potoyeee** [SalesforceAIResearch/uni2ts#14]
Especially regarding the validation set, removing it would allow training to commence. thank u

**Comment by liu-jc** [comment]
Hi @potoyeee , could you provide the error message here and the configuration file?

**Comment by potoyeee** [comment]
I follow the tutorial to create my own dataset.

hydra.errors.MissingConfigException: In 'default': Could not find 'data/price24'

Available options in 'data':
        etth1


我按照教程创建自己的数据集

**Comment by potoyeee** [comment]
This kind of error will occur when I wear the corresponding yaml.

Original Traceback (most recent call last):
  File "/home/ye/anaconda3/envs/darts_val/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ye/anaconda3/envs/darts_val/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ye/anaconda3/envs/darts_val/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ye/anaconda3/envs/darts_val/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 302, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/media/ye/CA8A5611E3656A9F/uni2ts/src/uni2ts/data/dataset.py", line 73, in __getitem__
    return self.transform(self._flatten_data(self._get_data(idx)))
  File "/media/ye/CA8A5611E3656A9F/uni2ts/src/uni2ts/transform/_base.py", line 57, in __call__
    data_entry = t(data_entry)
  File "/media/ye/CA8A5611E3656A9F/uni2ts/src/uni2ts/transform/crop.py", line 117, in __call__
    a, b = self._get_boundaries(data_entry)
  File "/media/ye/CA8A5611E3656A9F/uni2ts/src/uni2ts/transform/crop.py", line 142, in _get_boundaries
    assert time >= b > a >= 0

**Comment by potoyeee** [comment]
How do I set the "finetune/val_data/xxx.yaml"

**Comment by gorold** [comment]
You need to create a YAML file similar to [this](https://github.com/SalesforceAIResearch/uni2ts/blob/main/cli/conf/finetune/val_data/etth1.yaml), pointing to your own dataset. Depending on the generated file name, you should change the dataset field to `dataset: price24_eval`.

**Comment by potoyeee** [comment]
Thank you for your answer. It has a dimension error after setting up the validation set, which may be due to a problem with yaml file of the validation set. 
Ican finetune without validation set,loss decline but the performance of the test set is not as good as zero-shot, do you have any suggestions?

**Comment by gorold** [comment]
Hihi, it's overfitting. You could try training for fewer iterations, use early stopping, adding dropout, increasing weight decay, or collecting more data.

Regarding the validation set, I can't help you if you do not provide more details. If you follow the instructions carefully, you should be able to set up the validation set successfully. You could read the code implementation and the [hydra docs](https://hydra.cc/docs/intro/) for more information to debug.
