### ISSUE TITLE
plot_single()  -> Exception ignored in: <generator object PyTorchPredictor.predict at 0x000002A2CAF23220>

### ISSUE THREAD

**Issue by fritol** [SalesforceAIResearch/uni2ts#16]
when running the Getting started script:
at line `plot_single(...)` it throws:
```
Exception ignored in: <generator object PyTorchPredictor.predict at 0x0000020E3897EE30>
Traceback (most recent call last):
  File "H:\anaconda3\envs\310\lib\site-packages\gluonts\torch\model\predictor.py", line 89, in predict
  File "H:\anaconda3\envs\310\lib\site-packages\torch\autograd\grad_mode.py", line 84, in __exit__
TypeError: 'NoneType' object is not callable
```
python 3.10.13
gluonts                   0.14.4
matplotlib                3.8.4
conda on Win 10 

installed with 
`pip install -e .`

**Comment by gorold** [comment]
Hey, this is the same issue as #3, do not run this code in a script, try it in a notebook.

**Comment by fritol** [comment]
modified `plot_single()` with different colormaps ` cmap: str = 'viridis' # Add a new parameter for the color map`

```
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from gluonts import maybe
from gluonts.model import Forecast
import matplotlib.cm as cm

def plot_single(
    inp: dict,
    label: dict,
    forecast: Forecast,
    context_length: int,
    intervals: tuple[float, ...] = (0.5, 0.9),
    ax: Optional[plt.axis] = None,
    dim: Optional[int] = None,
    name: Optional[str] = None,
    show_label: bool = False,
    cmap: str = 'viridis' # Add a new parameter for the color map
):
    ax = maybe.unwrap_or_else(ax, plt.gca)
    print('A plotsingle')

    target = np.concatenate([inp["target"], label["target"]], axis=-1)
    start = inp["start"]
    if dim is not None:
        target = target[dim]
        forecast = forecast.copy_dim(dim)
    print('B plotsingle')
    index = pd.period_range(start, periods=len(target), freq=start.freq)
    ax.plot(
        index.to_timestamp()[-context_length - forecast.prediction_length :],
        target[-context_length - forecast.prediction_length :],
        label="target",
        color=cm.get_cmap(cmap)(0.5), # Use the color map for the plot color
    )
    print('C plotsingle')
    forecast.plot(
        intervals=intervals,
        ax=ax,
        color=cm.get_cmap(cmap)(0.75), # Use the color map for the forecast color
        name=name,
        show_label=show_label,
    )
    ax.set_xticks(ax.get_xticks())
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha="right")
    ax.legend(loc="lower left")
```
