### ISSUE TITLE
Getting Started Example Bugs

### ISSUE THREAD

**Issue by Sunsoft-io** [SalesforceAIResearch/uni2ts#34]
Hello,

I've run the Getting Started Example. 

There was a torch bug, which I could resolve by installing torch 2.2.2 (instead of 2.3.0) with "pip install torch==2.2.2".

But now there is the following message:
Exception ignored in: <generator object PyTorchPredictor.predict at 0x0000022E59436350>
Traceback (most recent call last):
  File "C:\Users\willi\AppData\Roaming\Python\Python311\site-packages\gluonts\torch\model\predictor.py", line 89, in predict
  File "C:\Users\willi\AppData\Roaming\Python\Python311\site-packages\torch\autograd\grad_mode.py", line 84, in __exit__TypeError: 'NoneType' object is not callable

Thanks...Willi

**Comment by gorold** [comment]
Have you pulled the latest version of the repo and getting started example? Also, please provide a minimal reproducible example for this error.

**Comment by Sunsoft-io** [comment]
Yes I've pulled the latest version of the repo. It installed torch 2.3.0 which also didn't work.

Next I will test Lag-Lama.

**Comment by Sunsoft-io** [comment]
I've used the Getting Started Example of huggingface.co, which is a little bit different.
