### ISSUE TITLE
RuntimeError: Please call `iter(combined_loader)` first.

### ISSUE THREAD

**Issue by catapples** [SalesforceAIResearch/uni2ts#68]
Thank you for your excellent work, but I have encountered the following error when reproducing it, which has been bothering me for a long time and remains unsolvable:

When I execute the Fine-tuning in the：
python -m cli.eval \ 
  run_name=example_eval_1 \
  model=moirai_1.0_R_small \
  model.patch_size=32 \ 
  model.context_length=1000 \
  data=etth1_test

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name   | Type         | Params
----------------------------------------
0 | module | MoiraiModule | 13.8 M
----------------------------------------
13.8 M    Trainable params
0         Non-trainable params
13.8 M    Total params
55.310    Total estimated model params size (MB)
Error executing job with overrides: ['run_name=example_run', 'model=moirai_1.0_R_small', 'data=etth1', 'val_data=etth1']                           
Traceback (most recent call last):
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 194, in run
    self.setup_data()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 258, in setup_data
    iter(self._data_fetcher)  # creates the iterator inside the fetcher
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 99, in __iter__
    super().__iter__()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 48, in __iter__
    self.iterator = iter(self.combined_loader)
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 335, in __iter__
    iter(iterator)
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 87, in __iter__
    super().__iter__()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 40, in __iter__
    self.iterators = [iter(iterable) for iterable in self.iterables]
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 40, in <listcomp>
    self.iterators = [iter(iterable) for iterable in self.iterables]
  File "/root/autodl-tmp/uni2ts/uni2ts/data/loader.py", line 368, in __iter__
    if self.iterator is None or not self.iterator.has_next():
  File "/root/autodl-tmp/uni2ts/uni2ts/data/loader.py", line 317, in has_next
    next_batch = next(self)
  File "/root/autodl-tmp/uni2ts/uni2ts/data/loader.py", line 284, in __next__
    while (data := self._next_batch()) is None:
  File "/root/autodl-tmp/uni2ts/uni2ts/data/loader.py", line 291, in _next_batch
    data = next(self.dataloader_iter)
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/uni2ts/uni2ts/data/dataset.py", line 73, in __getitem__
    return self.transform(self._flatten_data(self._get_data(idx)))
  File "/root/autodl-tmp/uni2ts/uni2ts/transform/_base.py", line 62, in __call__
    data_entry = t(data_entry)
  File "/root/autodl-tmp/uni2ts/uni2ts/transform/patch.py", line 87, in __call__
    constraints = self.patch_size_constraints(freq)
  File "/root/autodl-tmp/uni2ts/uni2ts/transform/patch.py", line 39, in __call__
    start, stop = self._get_boundaries(offset.n, norm_freq_str(offset.name))
  File "/root/autodl-tmp/uni2ts/uni2ts/transform/patch.py", line 73, in _get_boundaries
    start, stop = self.DEFAULT_RANGES[offset_name]
KeyError: 'h'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/autodl-tmp/uni2ts/cli/train.py", line 149, in <module>
    main()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
    raise ex
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/root/autodl-tmp/uni2ts/cli/train.py", line 142, in main
    trainer.fit(
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 68, in _call_and_handle_interrupt
    trainer._teardown()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1017, in _teardown
    loop.teardown()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 407, in teardown
    self._data_fetcher.teardown()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 75, in teardown
    self.reset()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 134, in reset
    super().reset()
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 71, in reset
    self.length = sized_len(self.combined_loader)
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/fabric/utilities/data.py", line 51, in sized_len
    length = len(dataloader)  # type: ignore [arg-type]
  File "/root/miniconda3/envs/uni2ts/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 342, in __len__
    raise RuntimeError("Please call `iter(combined_loader)` first.")
RuntimeError: Please call `iter(combined_loader)` first.

**Comment by catapples** [comment]
nothing
