### ISSUE TITLE
Errors when run evaluation scripts with checkpoints loaded from huggingface

### ISSUE THREAD

**Issue by HALF111** [SalesforceAIResearch/uni2ts#88]
**Describe the bug**
Hello, When I want to run https://github.com/SalesforceAIResearch/uni2ts/blob/main/project/moirai-1/eval/lsf_small.sh to evaluate moirai with checkpoints from huggingface, a problem occured: "type object 'MoiraiModule' has no attribute 'from_pretrained'". 
The problem seemingly exists in https://github.com/SalesforceAIResearch/uni2ts/blob/main/cli/conf/eval/model/moirai_1.0_R_small.yaml, where "from_pretrained" is not defined in MoiraiModule.

**To Reproduce**
Error report.
[2024-07-17 08:23:03,525][datasets][INFO] - PyTorch version 2.2.2 available.
[2024-07-17 08:23:03,527][datasets][INFO] - JAX version 0.4.26 available.
[2024-07-17 08:23:04,055][root][INFO] - using dataset already processed in path /home/lefeishen/.gluonts/datasets/us_births.
Error executing job with overrides: ['run_name=monash_eval', 'model=moirai_1.0_R_small', 'model.patch_size=32', 'model.context_length=1000', 'data=monash', 'data.dataset_name=us_births']
Traceback (most recent call last):
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: type object 'MoiraiModule' has no attribute 'from_pretrained'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 661, in _locate
    raise ImportError(
ImportError: Error loading 'uni2ts.model.moirai.MoiraiModule.from_pretrained':
AttributeError("type object 'MoiraiModule' has no attribute 'from_pretrained'")
Are you sure that 'from_pretrained' is an attribute of 'uni2ts.model.moirai.MoiraiModule'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lefeishen/uni2ts_reproduce/cli/eval.py", line 258, in <module>
    main()
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
    raise ex
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/lefeishen/uni2ts_reproduce/cli/eval.py", line 73, in main
    model = call(cfg.model, _partial_=True, _convert_="all")(
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'uni2ts.model.moirai.MoiraiModule.from_pretrained', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.module
^C^CTraceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lefeishen/uni2ts_reproduce/cli/eval.py", line 18, in <module>
    import torch
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/torch/__init__.py", line 1427, in <module>
    _C._initExtension(manager_path())
  File "/home/lefeishen/uni2ts_reproduce/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 1138, in <module>
    class HalfStorage(_CudaLegacyStorage):
KeyboardInterrupt

**Environment**
* Python version: 3.10.12
* PyTorch version: 2.2.2
* Lightning version: 2.2.2
* uni2ts version (have you pulled the latest version?): yes

**Comment by gorold** [comment]
please pull the latest version of the repo, and also reinstall the dependencies
